set nowritebackup
set nobackup
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=eol,indent,start
set whichwrap=b,s,<,>,~,[,]
syntax on
set background=dark
set textwidth=100
"set list
"set listchars=tab:»·,trail:·
set title

" Show matching brackets when text indicator is over them.
set showmatch

" Switch on filetype detection and loads indent file (indent.vim) for specific file types.
filetype indent on
filetype on
set autoindent " Copy indent from the row above.
set si " Smart indent.

" Number lines in display.
set nu

" Searches: highlight matches, and be case insensitive;
" unless they contain at least one capital letter.
set hlsearch
set ignorecase
set smartcase

fun! aaron:StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    let _s = @/
    %s/\s\+$//e
    let @/ = _s
    call cursor(l, c)
endfun
command! -nargs=0 -bar Strip call aaron:StripTrailingWhitespaces()

